export const TOGGLE_FORM = 'TOGGLE_FORM';
export const ADD_KOMBUCHA = 'ADD_KOMBUCHA';
export const DELETE_KOMBUCHA = 'DELETE_KOMBUCHA';
export const ORDER_KOMBUCHA = 'ORDER_KOMBUCHA';
export const RESTOCK_KOMBUCHA = 'RESTOCK_KOMBUCHA';